services:
  - type: web
    name: sams-back
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NAME_APP
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: BCRYPT_SALT
        value: "10"
      - key: ACCESS_TOKEN_EXPIRY
        value: 1d
      - key: REFRESH_TOKEN_EXPIRY
        value: 7d
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
